### ISSUE TITLE
foo-pre.c and BOOKWARE section

### ISSUE THREAD

**Issue by annoyinguser** [silv3rr/foo-tools#6]
foo-pre.c line 1310 
pre_replace(tmp, "KW", buf);

this will make BOOKWARE to BOO30ARE which is ofcourse pretty funny but not what you want if you have a BOOKWARE section :D 

a) remove, comment out that line, you still have CW for Calendar Week
b) rename to e.g. KAWE, this is what i usually do although i do not need KW/CW/KAWE anyway

**Comment by silv3rr** [comment]
hehe, not sure why it was done like that. I'll change to %CW %KW etc
