### ISSUE TITLE
Add mp3genres to mp3info

### ISSUE THREAD

**Issue by annoyinguser** [silv3rr/foo-tools#7]
Is there a way to add genres to `mp3info-0.8.5a/mp3info.h` ?
I would take the genres and numbers from `mp3genre/mp3genre.h` but I do not know how to add the numbers to index.

**Comment by silv3rr** [comment]
Just copy paste ... ?
Both use the same kind of array, starting from index 0:
```
genre_s[0] = "Blues"
genre_s[1] = "Classic Rock"
...
genre_s[193] = "Unknown"
```

Or just use mp3genre:
```
cd src/pre/mp3genre
make standalone
./mp3genre ~/01-American_Idiot.mp3
Punk Rock (121)
```
